/*
 Copyright 2023, NVIDIA CORPORATION & AFFILIATES
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

package k8sclient_test

import (
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/Mellanox/nvidia-k8s-ipam/pkg/cni/k8sclient"
)

const (
	kubeconfigTestData = `
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EVXlOREUwTURjeU5Gb1hEVE15TURVeU1URTBNRGN5TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkpJCnZUT2swNEtGVm51a0gyNUw3V2IvTFUxNVo4QUw4ZVFERXZZTnUyVys1eklaemxQTW5lUXYvWm1GcDloakpuUk0KQzc2N0s0cHpTMVNjcWlpUGxKaUlxNGhjcVJLdTA3bHZ6WTNiZWllNVhubXYzTm42YTM4THVHNVhud29pM3ZsdwpscUh4L3lHdEFicHRlUFA5K3FQRndySGxGMGlNMHZVb3BjNmt5cmUwR0RnVEkzUVdUQ3RmcDl2RDFydU1ER2krCnhjWnJueHVTcldkekdoWEV5d0FDWUtiaDEwUFQwbVJaK2p5MVViRFp3alk4VHN5WFl1WHpHci9KMUcvc0hOSFEKd1dmMnNDRVJnVjB1N2Z0eHhrZ0ZETXJOcllqcjJFUERhZ0lPeDdTTGFQVCtSNWN3bmc5Vml6ajNicnMzekppRwp3ZnNiZ1gxSTdlaHMzNmh6VXNVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJUjc1MWhlVG1Qcm4rb1N3NjltUXpWSEVpVWVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQkZpaWNkOTdERGR5QjUvbjg0agpZb2pIN1dNT1dDeTRwQ2ZuNWx0L2MyR2VRcDA3Y3NWbXlwUnY4YzQ3ZGYxVklIL09zcDlVczBoVWh1NFYybjBhCnZwM2svM1pSTEd3NVVzZGZoTkJrOTZWd0lRRFhVdER6NDZQU2dMUSsvREJqSitFbTJCanlyWm9PUkFGTDhsWkQKNzl2SndadXl6RC90UFFPL2xSZjRWZHYxQTl4R3U2QlJyRzdybmhBUVlxNDBBbGZ2dExlM2dqa1VFRVROZWFJOAorTERmeUs0cmVnTGc1emFNeDVvQmNyVzhiWHBxdTNFSlZHUXhoM3pVOVhmeDlJckdidE1zUHY2bXBEenV1TmhBCm5WemlPbC95TDhTMGdRTUt4WU9YdHpKYWdhU3JzQm82K3ZmenZkRHIzUnFST0VCSXU4eC9yRmsxNTNMdlUrMmUKdjY0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://7.7.7.7:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJUG9Bd0xoc2pRNFV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TWpBMU1qUXhOREEzTWpSYUZ3MHlNekExTWpReE5EQTNNamRhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXUyMWQ0V29kbGxTa2VhcDUKZUhqMnpIaGVFblNPaGxVbVdKanZ2VmtMdkd6RHR6ZkErMVo2b09xMkt1V0FtcVdjbjhIRjFuQU5aR0JyeFd2cgp3OHVPbzBYZHJpWEdDV1FkRi9sUTl0UXdIU1VWa1NTQzdIU0VwUHhXUVFjU3NoZnJVQ25YSjVkVllaWElkdHpnCnJURzVUZURENERnZCtPdUJhcmNiS096emFzcHpWalI0QStmUm1GQ1V2cVVSRTZSOTZRYmNVdGNzS05vQndpTisKcmtNNDFyOEJyUXBEZDNsUGhRWUdQdmN3TkdaNC8waUJFdDNLN1h3RUI2eFY4WDg1QjhoVkRvV0phRWV0NisragpUUEhUK3dmVzRoV3ovaFZ2S29HandiYlc5SEVPNnlYYitYRUZkL0o4R1JpeWtGZXVWYTJWWjJEc2tJRUdOUlpZCkpHYmE2UUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JTRWUrZFlYazVqNjUvcUVzT3Zaa00xUnhJbApIakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBTEdLbklSU05MaWtXenVpdDgyK0VTS21ZSWRZWVZwSVdJOFVQCmRnbXh0T0o2N3FWeWFtNnlqYzZRc3o4VE1jYk9lZzFwQ1hzbGVhd2VXZWpydmE3bzlhalVNTTNxNFBXSFg2aVMKTG13em5ockRiWTBsdC9qMGg1akJhMnlBOERoRml5WDBDR2ROMDVWSlg0aWZqL0I4ZC9tS1lXMzBDNHlJd2RFWApUdFZqRmgydzRFdlphNkpLZjRtMDRmSENtRjhMbzRNbkhJY0NObndGMmNwdHR4b1dHOWcxMEFjSnhkZy9SREhxClljZUR5bmUwYklDbGxrRlpFdStwdEIxcDkzVUI2RFY0VHh1VGpSZVFKYmt1Y2prQ1FtcTVmdXUrVjl5NE90TDMKK0VjVFpvSDUyV3dtZlk1TnJyT1hyTTl1UXpHSkQxaklYOE1LMVZlWjNDVmh4bkMxZ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdTIxZDRXb2RsbFNrZWFwNWVIajJ6SGhlRW5TT2hsVW1XSmp2dlZrTHZHekR0emZBCisxWjZvT3EyS3VXQW1xV2NuOEhGMW5BTlpHQnJ4V3Zydzh1T28wWGRyaVhHQ1dRZEYvbFE5dFF3SFNVVmtTU0MKN0hTRXBQeFdRUWNTc2hmclVDblhKNWRWWVpYSWR0emdyVEc1VGVERDREZ2QrT3VCYXJjYktPenphc3B6VmpSNApBK2ZSbUZDVXZxVVJFNlI5NlFiY1V0Y3NLTm9Cd2lOK3JrTTQxcjhCclFwRGQzbFBoUVlHUHZjd05HWjQvMGlCCkV0M0s3WHdFQjZ4VjhYODVCOGhWRG9XSmFFZXQ2KytqVFBIVCt3Zlc0aFd6L2hWdktvR2p3YmJXOUhFTzZ5WGIKK1hFRmQvSjhHUml5a0ZldVZhMlZaMkRza0lFR05SWllKR2JhNlFJREFRQUJBb0lCQVFDNXRLQnJZNEFUWHFSawo1SE5jMmNYM1RHQXhPd21vc2grL2N6RS9WRVpibVF6R3NkaGxjQWNxLzhRbGRxWlpGRFMrMmZrVEFvMVNZbk1GCjltdHc0WFRmODY2MUNUcFNQYjdSN1RhNmlmMXVNenRPUjNYdG9YbDRHNG0rL3FvWWliaWZBZ1hyZFhla3JBc24KTXF6dkRqQ0RxR3VMOHk1SFg5a29DbXMvdnA5a3M2WTlla3czdHNIMVNHZE5iNml2MU81bjV4OHRjNXQ3QUUyMgpzVHdEZThlZXBjZzV2MHhzRm9iU1dtNmo2a3ZCcnp2b2l4bmZ1ZWdMQ1FvcDMza1lKTUthSE95eFlZNW5YZnY5ClhNeHNPWldwcU9RU09ZVkdRZTdpUGc4aDYvOWxSZHYvbCtlTWd3MUtmaUlocENWNTdDbVMvd0pFY1lDSW1reFcKMXMweCs4OGRBb0dCQU9xMGtOU0lhSmRDaVJqaXZqWC9rSTY3K3lTN1ZGYStRbm5EN2ZvNHJGZ05nMzJGTWZmNgpQTGRvQThYRkJyYy9iZyttTGlFM3dldzBYR2lxZTlmdklVQXlnZ0FsNnlvdzdINnMwanZrcEd2UElaMzNyaHBOCmlCNzFmYVRZaldWYjgzWkk3YXVEeG1Mb1N3bStlbXJ5bWxlbXIwWlphZmI2QnN2VjVqSFkwV1ZyQW9HQkFNeHUKcjNxVmVEbzZmUTJKRDJrcUtDWmwybzRZaE9wZkxmUnJ3OFMxdFozWXAxRmRFcnVDMXN3NGRYRG9TcHJpcEdTQgo5a200VUdkSXg4ZjdCV1BhV0Nod0tXMCtiWnhZOHFoL2JKZUhRQTN2MEp4eTlaZUp1UEtBMnhtR3FoTkN3USsvClo4NGFWNkxuNnp6aFRqT0FjdStEb091TDV0akl3R3c1RlkzUzJRSDdBb0dBWFIzUVRCSG1kUVIzd2dETGVEN3gKaWo5NFQwVm5HNWNXWnByZVFxVFRjNGZCQUQ2azZYNUZNbnE0N0hEVHprWURFNEJaMHVIOU5RbzlFMlY0QnQ2ZgpzWW1ZWEJpdktTa0oydVFUOEtFd3Zua0tIRk1VcHVqVnRYcXVJNFdxNjJqRXVjd0xSejNicW9nQXBWZ0YxNEp5Cnk0MmRBbXNkQ0ZoLzg4VGtOQ2lTUXdzQ2dZRUFvQTU5QjEzbFhybVNWVG1kUGpwS2F4M055dmo1ZjhKN2FXWEMKUmMzNjN4WFVra2hydFRIUVdONVBYTklTTDBnSmE4T3cvN0QyQ3BlYUMwSEd5NUlVK2J3dlF4L2drOHUwV1NaQwo4RFJ0ZXp2cXVjTHI4L1JaUUV5UXZtQ0g0a0tlZzJUWnNpMC90Z1VjVVhNWlZndFljWncrTG8wL2RUVmdLcHRhCis4bzhLMmNDZ1lFQXk4dC9sQkZwRzNNdjBBaTlIT2VnUEhlSGZOekd1a0RpbVpmWEdqWW1qMEJOYVZjRkZya2gKaTZ6SzhPbml6bWlFLzI2bm45RG5vV3NDbm9vVVRjMnpuWlhJVCtKYXhGNnVDcG51M2JKaTVrUzBreFZYcWpmUQpWb2ZFeW9QQkdmYWVRSkhpNytYemh2UFVocDFUQkNMbGlLOUxmZkkrV0ZEU0poazZIMytWVFJBPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
`
)

var _ = Describe("k8sclient tests", func() {
	var (
		tmpDir                string
		validKubeconfigPath   string
		invalidKubeconfigPath string
	)

	BeforeEach(func() {
		var err error
		tmpDir := GinkgoT().TempDir()

		validKubeconfigPath = filepath.Join(tmpDir, "kube.conf")
		invalidKubeconfigPath = filepath.Join(tmpDir, "kube-invalid.conf")

		err = os.WriteFile(validKubeconfigPath, []byte(kubeconfigTestData), 0744)
		Expect(err).NotTo(HaveOccurred())

		err = os.WriteFile(invalidKubeconfigPath, []byte("This is an invalid kubeconfig content"), 0744)
		Expect(err).NotTo(HaveOccurred())
	})

	Context("FromKubeconfig", func() {
		It("creates k8s deffered client if kubeconfig valid", func() {
			_, err := k8sclient.FromKubeconfig(validKubeconfigPath)
			Expect(err).ToNot(HaveOccurred())
		})

		It("fails if kubeconfig path not found", func() {
			_, err := k8sclient.FromKubeconfig(filepath.Join(tmpDir, "does-not-exist.conf"))
			Expect(err).To(HaveOccurred())
		})

		It("fails if kubeconfig file contains garbage", func() {
			_, err := k8sclient.FromKubeconfig(invalidKubeconfigPath)
			Expect(err).To(HaveOccurred())
		})
	})
})
