apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node
subjects:
  - kind: ServiceAccount
    name: node
    namespace: system
