kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node
  namespace: system
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged
