apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-nv-ipam-nvidia-com-v1alpha1-ippool
    failurePolicy: Fail
    name: validate-ippool.nv-ipam.nvidia.com
    rules:
      - apiGroups:
          - nv-ipam.nvidia.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ippools
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-nv-ipam-nvidia-com-v1alpha1-cidrpool
    failurePolicy: Fail
    name: validate-cidrpool.nv-ipam.nvidia.com
    rules:
      - apiGroups:
          - nv-ipam.nvidia.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - cidrpools
    sideEffects: None
