kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node
subjects:
  - kind: ServiceAccount
    name: node
    namespace: system
