kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - nv-ipam.nvidia.com
    resources:
      - ippools
    verbs:
      - get
      - list
      - watch
