---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nv-ipam-node
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nv-ipam-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nv-ipam-node
subjects:
- kind: ServiceAccount
  name: nv-ipam-node
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nv-ipam-node
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-nv-ipam-node-ds
  namespace: kube-system
  labels:
    tier: node
    app: nv-ipam-node
    name: nv-ipam-node
spec:
  selector:
    matchLabels:
      name: nv-ipam-node
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: nv-ipam-node
        name: nv-ipam-node
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: nv-ipam-node
      containers:
      - name: kube-nv-ipam-node
        image: ghcr.io/mellanox/nvidia-k8s-ipam:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/ipam-node"]
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin          
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: hostlocalcnibin
          mountPath: /host/var/lib/cni/nv-ipam/bin
        - name: hostlocalcnistate
          mountPath: /host/var/lib/cni/nv-ipam/state/host-local
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
            type: DirectoryOrCreate        
        - name: cni
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
        - name: hostlocalcnibin
          hostPath:
            path: /var/lib/cni/nv-ipam/bin
            type: DirectoryOrCreate
        - name: hostlocalcnistate
          hostPath:
            path: /var/lib/cni/nv-ipam/state/host-local
            type: DirectoryOrCreate
