// Copyright 2023, NVIDIA CORPORATION & AFFILIATES
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: nvidia/ipam/daemon/v1/daemon.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IPAMBackendService_Allocate_FullMethodName    = "/nvidia.ipam.daemon.v1.IPAMBackendService/Allocate"
	IPAMBackendService_IsAllocated_FullMethodName = "/nvidia.ipam.daemon.v1.IPAMBackendService/IsAllocated"
	IPAMBackendService_Deallocate_FullMethodName  = "/nvidia.ipam.daemon.v1.IPAMBackendService/Deallocate"
)

// IPAMBackendServiceClient is the client API for IPAMBackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPAMBackendServiceClient interface {
	// Allocate is called as a part of CMD_ADD flow
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
	// IsAllocated is called as a part of CMD_CHECk flow
	IsAllocated(ctx context.Context, in *IsAllocatedRequest, opts ...grpc.CallOption) (*IsAllocatedResponse, error)
	// Deallocate is called as a part of CMD_DEL flow
	Deallocate(ctx context.Context, in *DeallocateRequest, opts ...grpc.CallOption) (*DeallocateResponse, error)
}

type iPAMBackendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPAMBackendServiceClient(cc grpc.ClientConnInterface) IPAMBackendServiceClient {
	return &iPAMBackendServiceClient{cc}
}

func (c *iPAMBackendServiceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, IPAMBackendService_Allocate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMBackendServiceClient) IsAllocated(ctx context.Context, in *IsAllocatedRequest, opts ...grpc.CallOption) (*IsAllocatedResponse, error) {
	out := new(IsAllocatedResponse)
	err := c.cc.Invoke(ctx, IPAMBackendService_IsAllocated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPAMBackendServiceClient) Deallocate(ctx context.Context, in *DeallocateRequest, opts ...grpc.CallOption) (*DeallocateResponse, error) {
	out := new(DeallocateResponse)
	err := c.cc.Invoke(ctx, IPAMBackendService_Deallocate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IPAMBackendServiceServer is the server API for IPAMBackendService service.
// All implementations must embed UnimplementedIPAMBackendServiceServer
// for forward compatibility
type IPAMBackendServiceServer interface {
	// Allocate is called as a part of CMD_ADD flow
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	// IsAllocated is called as a part of CMD_CHECk flow
	IsAllocated(context.Context, *IsAllocatedRequest) (*IsAllocatedResponse, error)
	// Deallocate is called as a part of CMD_DEL flow
	Deallocate(context.Context, *DeallocateRequest) (*DeallocateResponse, error)
	mustEmbedUnimplementedIPAMBackendServiceServer()
}

// UnimplementedIPAMBackendServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIPAMBackendServiceServer struct {
}

func (UnimplementedIPAMBackendServiceServer) Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedIPAMBackendServiceServer) IsAllocated(context.Context, *IsAllocatedRequest) (*IsAllocatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAllocated not implemented")
}
func (UnimplementedIPAMBackendServiceServer) Deallocate(context.Context, *DeallocateRequest) (*DeallocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deallocate not implemented")
}
func (UnimplementedIPAMBackendServiceServer) mustEmbedUnimplementedIPAMBackendServiceServer() {}

// UnsafeIPAMBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPAMBackendServiceServer will
// result in compilation errors.
type UnsafeIPAMBackendServiceServer interface {
	mustEmbedUnimplementedIPAMBackendServiceServer()
}

func RegisterIPAMBackendServiceServer(s grpc.ServiceRegistrar, srv IPAMBackendServiceServer) {
	s.RegisterService(&IPAMBackendService_ServiceDesc, srv)
}

func _IPAMBackendService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMBackendServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMBackendService_Allocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMBackendServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMBackendService_IsAllocated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAllocatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMBackendServiceServer).IsAllocated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMBackendService_IsAllocated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMBackendServiceServer).IsAllocated(ctx, req.(*IsAllocatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPAMBackendService_Deallocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeallocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPAMBackendServiceServer).Deallocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IPAMBackendService_Deallocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPAMBackendServiceServer).Deallocate(ctx, req.(*DeallocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IPAMBackendService_ServiceDesc is the grpc.ServiceDesc for IPAMBackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPAMBackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nvidia.ipam.daemon.v1.IPAMBackendService",
	HandlerType: (*IPAMBackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _IPAMBackendService_Allocate_Handler,
		},
		{
			MethodName: "IsAllocated",
			Handler:    _IPAMBackendService_IsAllocated_Handler,
		},
		{
			MethodName: "Deallocate",
			Handler:    _IPAMBackendService_Deallocate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvidia/ipam/daemon/v1/daemon.proto",
}
