name: "Build, Test, Lint"
on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-ci-reusable.yml@main
    with:
      test-command: make cov-report
      coverage-file: lcov.info
      coverage-format: lcov
      validate-command: |
        go mod tidy
        git diff --exit-code
        go mod vendor
        git diff --exit-code
        make grpc-check
  build-image:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/image-build-reusable.yml@main
    with:
      build-args: GOPROXY=https://proxy.golang.org,direct
